### ISSUE TITLE
Require Error

### ISSUE THREAD

**Issue by eduardoscottini** [dry-rb/dry-struct#118]
I can't do a `require 'dry-struct'` in my gem.

My gemspec:
```ruby
  spec.required_ruby_version = '~> 2.2'

  spec.add_dependency "savon", "~> 2.12.0"
  spec.add_dependency "dry-types"
  spec.add_dependency "dry-struct"
  spec.add_dependency "ox"
  spec.add_development_dependency "bundler", "~> 1.16"
  spec.add_development_dependency "rake", "~> 10.0"
  spec.add_development_dependency "pry", "~> 0.12.2"
  spec.add_development_dependency "rspec", "~> 3.0"
  spec.add_development_dependency "webmock"
  spec.add_development_dependency "simplecov"
  spec.add_development_dependency "simplecov-console"
```

I'm getting this error: 
```
⋊> ~/p/nfse on master ⨯ bundle console                                                                                                                                                                     16:07:02
irb(main):001:0>  require 'dry-struct'
SyntaxError: /usr/share/rvm/gems/ruby-2.2.10@nfse/gems/dry-logic-0.6.1/lib/dry/logic/rule/interface.rb:67: syntax error, unexpected <<, expecting ')'
          module_eval(<<~RUBY, __FILE__, __LINE__ + 1)
                        ^
/usr/share/rvm/gems/ruby-2.2.10@nfse/gems/dry-logic-0.6.1/lib/dry/logic/rule/interface.rb:67: Can't assign to __FILE__
          module_eval(<<~RUBY, __FILE__, __LINE__ + 1)
                                        ^
/usr/share/rvm/gems/ruby-2.2.10@nfse/gems/dry-logic-0.6.1/lib/dry/logic/rule/interface.rb:67: Can't assign to __LINE__
          module_eval(<<~RUBY, __FILE__, __LINE__ + 1)
                                                   ^
/usr/share/rvm/gems/ruby-2.2.10@nfse/gems/dry-logic-0.6.1/lib/dry/logic/rule/interface.rb:67: syntax error, unexpected '+', expecting '='
          module_eval(<<~RUBY, __FILE__, __LINE__ + 1)
                                                   ^
/usr/share/rvm/gems/ruby-2.2.10@nfse/gems/dry-logic-0.6.1/lib/dry/logic/rule/interface.rb:100: syntax error, unexpected <<, expecting ')'
          module_eval(<<~RUBY, __FILE__, __LINE__ + 1)
                        ^
/usr/share/rvm/gems/ruby-2.2.10@nfse/gems/dry-logic-0.6.1/lib/dry/logic/rule/interface.rb:100: Can't assign to __FILE__
          module_eval(<<~RUBY, __FILE__, __LINE__ + 1)
                                        ^
/usr/share/rvm/gems/ruby-2.2.10@nfse/gems/dry-logic-0.6.1/lib/dry/logic/rule/interface.rb:100: Can't assign to __LINE__
          module_eval(<<~RUBY, __FILE__, __LINE__ + 1)
                                                   ^
/usr/share/rvm/gems/ruby-2.2.10@nfse/gems/dry-logic-0.6.1/lib/dry/logic/rule/interface.rb:100: syntax error, unexpected '+', expecting '='
          module_eval(<<~RUBY, __FILE__, __LINE__ + 1)
                                                   ^
/usr/share/rvm/gems/ruby-2.2.10@nfse/gems/dry-logic-0.6.1/lib/dry/logic/rule/interface.rb:119: syntax error, unexpected <<, expecting ')'
          module_eval(<<~RUBY, __FILE__, __LINE__ + 1)
                        ^
/usr/share/rvm/gems/ruby-2.2.10@nfse/gems/dry-logic-0.6.1/lib/dry/logic/rule/interface.rb:119: Can't assign to __FILE__
          module_eval(<<~RUBY, __FILE__, __LINE__ + 1)
                                        ^
/usr/share/rvm/gems/ruby-2.2.10@nfse/gems/dry-logic-0.6.1/lib/dry/logic/rule/interface.rb:119: Can't assign to __LINE__
          module_eval(<<~RUBY, __FILE__, __LINE__ + 1)
                                                   ^
/usr/share/rvm/gems/ruby-2.2.10@nfse/gems/dry-logic-0.6.1/lib/dry/logic/rule/interface.rb:119: syntax error, unexpected '+', expecting '='
          module_eval(<<~RUBY, __FILE__, __LINE__ + 1)
                                                   ^
/usr/share/rvm/gems/ruby-2.2.10@nfse/gems/dry-logic-0.6.1/lib/dry/logic/rule/interface.rb:121: syntax error, unexpected keyword_if, expecting ')'
              if #{application}
                ^
/usr/share/rvm/gems/ruby-2.2.10@nfse/gems/dry-logic-0.6.1/lib/dry/logic/rule/interface.rb:125: syntax error, unexpected keyword_end, expecting ')'
/usr/share/rvm/gems/ruby-2.2.10@nfse/gems/dry-logic-0.6.1/lib/dry/logic/rule/interface.rb:130: syntax error, unexpected keyword_end, expecting ')'
/usr/share/rvm/gems/ruby-2.2.10@nfse/gems/dry-logic-0.6.1/lib/dry/logic/rule/interface.rb:141: syntax error, unexpected keyword_end, expecting '}'
	from /usr/share/rvm/gems/ruby-2.2.10@nfse/gems/dry-logic-0.6.1/lib/dry/logic/rule.rb:6:in `require'
	from /usr/share/rvm/gems/ruby-2.2.10@nfse/gems/dry-logic-0.6.1/lib/dry/logic/rule.rb:6:in `<top (required)>'
	from /usr/share/rvm/gems/ruby-2.2.10@nfse/gems/dry-logic-0.6.1/lib/dry/logic/rule_compiler.rb:3:in `require'
	from /usr/share/rvm/gems/ruby-2.2.10@nfse/gems/dry-logic-0.6.1/lib/dry/logic/rule_compiler.rb:3:in `<top (required)>'
	from /usr/share/rvm/gems/ruby-2.2.10@nfse/gems/dry-types-0.13.4/lib/dry/types/constraints.rb:1:in `require'
	from /usr/share/rvm/gems/ruby-2.2.10@nfse/gems/dry-types-0.13.4/lib/dry/types/constraints.rb:1:in `<top (required)>'
	from /usr/share/rvm/gems/ruby-2.2.10@nfse/gems/dry-types-0.13.4/lib/dry/types/constrained.rb:2:in `require'
	from /usr/share/rvm/gems/ruby-2.2.10@nfse/gems/dry-types-0.13.4/lib/dry/types/constrained.rb:2:in `<top (required)>'
	from /usr/share/rvm/gems/ruby-2.2.10@nfse/gems/dry-types-0.13.4/lib/dry/types/builder.rb:73:in `require'
	from /usr/share/rvm/gems/ruby-2.2.10@nfse/gems/dry-types-0.13.4/lib/dry/types/builder.rb:73:in `<top (required)>'
	from /usr/share/rvm/gems/ruby-2.2.10@nfse/gems/dry-types-0.13.4/lib/dry/types/definition.rb:1:in `require'
	from /usr/share/rvm/gems/ruby-2.2.10@nfse/gems/dry-types-0.13.4/lib/dry/types/definition.rb:1:in `<top (required)>'
	from /usr/share/rvm/gems/ruby-2.2.10@nfse/gems/dry-types-0.13.4/lib/dry/types.rb:17:in `require'
	from /usr/share/rvm/gems/ruby-2.2.10@nfse/gems/dry-types-0.13.4/lib/dry/types.rb:17:in `<top (required)>'
	from /usr/share/rvm/gems/ruby-2.2.10@nfse/gems/dry-types-0.13.4/lib/dry-types.rb:1:in `require'
	from /usr/share/rvm/gems/ruby-2.2.10@nfse/gems/dry-types-0.13.4/lib/dry-types.rb:1:in `<top (required)>'
... 3 levels...
	from /usr/share/rvm/gems/ruby-2.2.10@nfse/gems/dry-struct-0.6.0/lib/dry-struct.rb:1:in `<top (required)>'
	from (irb):1:in `require'
	from (irb):1
	from /usr/share/rvm/rubies/ruby-2.2.10/lib/ruby/site_ruby/2.2.0/bundler/cli/console.rb:19:in `run'
	from /usr/share/rvm/rubies/ruby-2.2.10/lib/ruby/site_ruby/2.2.0/bundler/cli.rb:455:in `console'
	from /usr/share/rvm/rubies/ruby-2.2.10/lib/ruby/site_ruby/2.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /usr/share/rvm/rubies/ruby-2.2.10/lib/ruby/site_ruby/2.2.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/share/rvm/rubies/ruby-2.2.10/lib/ruby/site_ruby/2.2.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
	from /usr/share/rvm/rubies/ruby-2.2.10/lib/ruby/site_ruby/2.2.0/bundler/cli.rb:27:in `dispatch'
	from /usr/share/rvm/rubies/ruby-2.2.10/lib/ruby/site_ruby/2.2.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
	from /usr/share/rvm/rubies/ruby-2.2.10/lib/ruby/site_ruby/2.2.0/bundler/cli.rb:18:in `start'
	from /usr/share/rvm/rubies/ruby-2.2.10/bin/bundle:30:in `block in <main>'
	from /usr/share/rvm/rubies/ruby-2.2.10/lib/ruby/site_ruby/2.2.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
	from /usr/share/rvm/rubies/ruby-2.2.10/bin/bundle:22:in `<main>'
	from /usr/share/rvm/gems/ruby-2.2.10@nfse/bin/ruby_executable_hooks:24:in `eval'
	from /usr/share/rvm/gems/ruby-2.2.10@nfse/bin/ruby_executable_hooks:24:in `<main>'
```

**Comment by paul** [comment]
Looks like you're on a fairly old version of Ruby (2.2.10), for which support was dropped nearly a year ago: https://www.ruby-lang.org/en/news/2018/06/20/support-of-ruby-2-2-has-ended/

dry-struct requires at least 2.4.0: https://github.com/dry-rb/dry-struct/blob/master/dry-struct.gemspec#L30

**Comment by solnic** [comment]
Like Paul said, we dropped support for MRI < 2.4. Please upgrade.
