### ISSUE TITLE
Array of sum types of structs throwing exceptions

### ISSUE THREAD

**Issue by mull** [dry-rb/dry-struct#134]
An attribute of type `Types.Array(StructA | StructB)` does not handle coercion(?) correctly when initialised with instances of those structs or hashes that can be coerced into one of those structs.

```ruby
require 'dry-struct'

module Types
  include Dry.Types()
end

class Foo < Dry::Struct
   attribute :kind, Types.Constant(:foo)
end

class Bar < Dry::Struct
  attribute :kind, Types.Constant(:bar)
end

Either = Foo | Bar 

class FooBar < Dry::Struct
  attribute :value, Either
end


foo = { value: {kind: :foo} }
bar = { value: {kind: :bar} }

# This works fine
foo_struct = FooBar.new(foo)
bar_struct = FooBar.new(bar)


class OtherThing < Dry::Struct
  attribute :values, Types.Array(Either)
end

# These will both throw an error
OtherThing.new(values: [foo_struct, bar_struct].map(&:to_h))
OtherThing.new(values: [foo_struct, bar_struct])
```

Running the script provides exception. The first failing line produces two(?) exceptions:

```
/Users/mull/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dry-types-1.2.1/lib/dry/types/schema.rb:371:in `block in resolve_missing_keys': :kind is missing in Hash input (Dry::Types::MissingKeyError)

# and the next one

/Users/mull/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dry-struct-1.1.1/lib/dry/struct/class_interface.rb:234:in `rescue in new': [Bar.new] :kind is missing in Hash input (Dry::Struct::Error)
```

**Expected behavior**
I expect this to initialise correctly. We can find our way back to one of Foo or Bar by running `.try()` on each of the options.

Correctly would be: 

```
OtherThing<
  values: [
    FooBar<value: Foo<kind: :foo>>, 
    FooBar<value: Bar<kind: :bar>>
  ]
>
```

**Your environment**

- Affects my production application: **NO**
- Ruby version: 2.6.3
- OS: macOS 10.14.6

**Comment by flash-gordon** [comment]
You have incorrect definition of `OtherThing`, it must be
```ruby
class OtherThing < Dry::Struct
  attribute :values, Types.Array(FooBar)
end
```
