### ISSUE TITLE
Got stack level too deep (SystemStackError) when use attribute name hash

### ISSUE THREAD

**Issue by galetahub** [dry-rb/dry-struct#56]
The following example is raise stack level too deep (SystemStackError):
```ruby
require 'dry-struct'

module Types
  include Dry::Types.module
end

class Bar < Dry::Struct
  attribute :hash, Types::Strict::String
end

bar = Bar.new(hash: 'test')
bar.hash
```

Stacktrace:
```
/Volumes/Data/mario/.rvm/gems/ruby-2.3.4/gems/dry-equalizer-0.2.0/lib/dry/equalizer.rb:78:in `lambda': stack level too deep (SystemStackError)
	from /Volumes/Data/mario/.rvm/gems/ruby-2.3.4/gems/dry-equalizer-0.2.0/lib/dry/equalizer.rb:78:in `to_proc'
	from /Volumes/Data/mario/.rvm/gems/ruby-2.3.4/gems/dry-equalizer-0.2.0/lib/dry/equalizer.rb:78:in `block in define_hash_method'
	from /Volumes/Data/mario/.rvm/gems/ruby-2.3.4/gems/dry-equalizer-0.2.0/lib/dry/equalizer.rb:78:in `map'
	from /Volumes/Data/mario/.rvm/gems/ruby-2.3.4/gems/dry-equalizer-0.2.0/lib/dry/equalizer.rb:78:in `block in define_hash_method'
	from /Volumes/Data/mario/.rvm/gems/ruby-2.3.4/gems/dry-equalizer-0.2.0/lib/dry/equalizer.rb:78:in `map'
	from /Volumes/Data/mario/.rvm/gems/ruby-2.3.4/gems/dry-equalizer-0.2.0/lib/dry/equalizer.rb:78:in `block in define_hash_method'
	from /Volumes/Data/mario/.rvm/gems/ruby-2.3.4/gems/dry-equalizer-0.2.0/lib/dry/equalizer.rb:78:in `map'
	from /Volumes/Data/mario/.rvm/gems/ruby-2.3.4/gems/dry-equalizer-0.2.0/lib/dry/equalizer.rb:78:in `block in define_hash_method'
	 ... 5943 levels...
	from /Volumes/Data/mario/.rvm/gems/ruby-2.3.4/gems/dry-equalizer-0.2.0/lib/dry/equalizer.rb:78:in `block in define_hash_method'
	from /Volumes/Data/mario/.rvm/gems/ruby-2.3.4/gems/dry-equalizer-0.2.0/lib/dry/equalizer.rb:78:in `map'
	from /Volumes/Data/mario/.rvm/gems/ruby-2.3.4/gems/dry-equalizer-0.2.0/lib/dry/equalizer.rb:78:in `block in define_hash_method'
	from tmp/test.rb:12:in `<main>'
```

**Comment by solnic** [comment]
Sorry but it makes no sense to do anything with this, calling an attribute the same as one of the `Object` methods (esp an important one like `#hash`) will always give you trouble. Alternatively we can raise an error if an attribute name is the same as one of the existing methods from `Object`.

**Comment by flash-gordon** [comment]
@solnic instead, we could add an option to equalizer to use ivars rather than methods, this way the value of `hash` attribute will be available with `struct[:hash]`, similar to how it works in AR, wdyt?

**Comment by solnic** [comment]
@flash-gordon hm yeah sounds like a good idea

**Comment by flash-gordon** [comment]
I made it work via `[]`:
```ruby
irb(main):002:0> bar.hash
=> -3247116894466213490
irb(main):003:0> bar[:hash]
=> "test"
```
